// GENERATED by scripts/embed-clips.mjs — do not edit by hand.
export const CLIPS = [
  {
    "id": "brand",
    "name": "DeepSeek 品牌片头",
    "ext": ".mp4",
    "bytes": 2487782,
    "sha256": "d6167e0123f31a66",
    "b64": 3317044
  },
  {
    "id": "cyberpunk",
    "name": "DeepSeek 赛博朋克片头",
    "ext": ".mp4",
    "bytes": 3785007,
    "sha256": "eedd97fdae7a28b4",
    "b64": 5046676
  },
  {
    "id": "awakening",
    "name": "DeepSeek 数字角色苏醒",
    "ext": ".mp4",
    "bytes": 5441673,
    "sha256": "ea2e4897de04eb1b",
    "b64": 7255564
  },
  {
    "id": "startup",
    "name": "DeepSeek 启动问题",
    "ext": ".mp4",
    "bytes": 5939520,
    "sha256": "b63f05c313a033ae",
    "b64": 7919360
  }
]
